# fly.toml app configuration file generated for jeanwalker on 2023-07-18T21:35:14-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jeanwalker"
primary_region = "den"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[build.args]
  BP_KEEP_FILES = "static/*:templates/*"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
